# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
    
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
        REACT_APP_APIKEY: ${{secrets.REACT_APP_APIKEY}}
        REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
        REACT_APP_DATABASE_URL: ${{secrets.REACT_APP_DATABASE_URL}}
        REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
        REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
        REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
        REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git config user.email ${{ secrets.USER_EMAIL }}
    - run: git config user.name ${{ secrets.USER_NAME }}
    - run: git remote set-url origin https://${{ secrets.CI_GITHUB_TOKEN }}@github.com/${{ secrets.USER_NAME }}/admin.git
    - run: npm run deploy
      
